# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout SocketManager
        uses: actions/checkout@master
        with:
          path: SocketManager
          repository: ZeroxCorbin/SocketManager
      - name: Restore NuGet
        run: nuget restore $Env:GITHUB_WORKSPACE\SocketManager\SocketManager.sln
      - name: Checkout SimpleModbus
        uses: actions/checkout@master
        with:
          path: SimpleModbus
          repository: ZeroxCorbin/SimpleModbus
      - name: Restore NuGet
        run: nuget restore $Env:GITHUB_WORKSPACE\SimpleModbus\SimpleModbus.sln
      - name: Checkout TM_Comms_WPF
        uses: actions/checkout@master
        with:
          path: TM_Comms_WPF
      - name: Restore NuGet
        run: nuget restore $Env:GITHUB_WORKSPACE\TM_Comms_WPF\TM_Comms_WPF.sln
      - name: Build DotNET
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\TM_Comms_WPF\TM_Comms_WPF.sln
